django_blog/blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='blog/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='blog/logged_out.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/<int:pk>/comments/new/', views.CommentCreateView.as_view(), name='comment_create'),
    path('comment/<int:pk>/update/', views.CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view(), name='comment_delete'),
    path("search/", views.post_search, name="post_search"),
    path("tags/<slug:tag_slug>/", views.PostByTagListView.as_view(), name="posts_by_tag"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_blog/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

django_blog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from taggit.managers import TaggableManager

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    tags = TaggableManager()
    class Meta:
        ordering = ['-published_date']

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_at']

    def __str__(self):
        return f'Comment by {self.author.username} on {self.post.title[:20]}'
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.post.pk})
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    bio = models.TextField(blank=True)
    image = models.ImageField(upload_to='profile_pics/', blank=True, null=True)

    def __str__(self):
        return f'{self.user.username} Profile'
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.pk})
    
@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_profile(sender, instance, **kwargs):
    try:
        instance.profile.save()
    except Exception:
        pass

django_blog/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Post, Comment
from taggit.forms import TagWidget 

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text='Required')

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'image')

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'content', 'tags']
        widgets = {
            'tags': TagWidget(),
        }

    def __init__(self, *args, **kwargs):
        instance = kwargs.get('instance')
        initial = kwargs.get('initial', {})
        if instance:
            initial['tags'] = ', '.join([t.name for t in instance.tags.all()])
            kwargs['initial'] = initial
        super().__init__(*args, **kwargs)

class CommentForm(forms.ModelForm):
    content = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 3, 'placeholder': 'Write your comment...'}),
        max_length=2000,
        label=''
    )

    class Meta:
        model = Comment
        fields = ['content']

django_blog/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, UserUpdateForm, ProfileForm, PostForm, CommentForm
from .models import Post, Comment
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from taggit.models import Tag


def post_list(request):
    posts = Post.objects.all()
    return render(request, 'blog/post_list.html', {'posts': posts})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

def post_list(request):
    posts = Post.objects.all()
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, 'Account created successfully. You can now log in.')
            return redirect('blog:login')
    else:
        form = CustomUserCreationForm()
    return render(request, 'blog/register.html', {'form': form})

def post_search(request):
    query = request.GET.get("q")
    results = []

    if query:
        results = Post.objects.filter(
            Q(title__icontains=query) | 
            Q(content__icontains=query) |     
            Q(tags__name__icontains=query)
        ).distinct()

    return render(request, "blog/post_search.html", {"query": query, "results": results})

class PostByTagListView(ListView):
    model = Post
    template_name = "blog/post_by_tag.html"
    context_object_name = "posts"
    paginate_by = 5 

    def get_queryset(self):
        tag_slug = self.kwargs.get("tag_slug")
        self.tag = get_object_or_404(Tag, slug=tag_slug)
        return Post.objects.filter(tags__in=[self.tag])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag"] = self.tag
        return context

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Your profile has been updated.')
            return redirect('blog:profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'blog/profile.html', context)

class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html' 
    context_object_name = 'posts'
    paginate_by = 5 

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        return context

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_form.html'

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_form.html'

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'blog/post_confirm_delete.html'
    success_url = reverse_lazy('blog:post_list')

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author
    
class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'blog/comment_form.html'

    def dispatch(self, request, *args, **kwargs):
        self.post = get_object_or_404(Post, pk=kwargs.get('post_id'))
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post = self.post
        return super().form_valid(form)

    def get_success_url(self):
        return self.post.get_absolute_url()

class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'blog/comment_form.html'
    pk_url_kwarg = 'comment_id'

    def test_func(self):
        comment = self.get_object()
        return self.request.user == comment.author

    def get_success_url(self):
        return self.get_object().post.get_absolute_url()

class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    template_name = 'blog/comment_confirm_delete.html'
    pk_url_kwarg = 'comment_id'

    def test_func(self):
        comment = self.get_object()
        return self.request.user == comment.author

    def get_success_url(self):
        return self.get_object().post.get_absolute_url()

django_blog/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block title %}My Django Blog{% endblock %}</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
</head>
<body>
  <header>
    <h1><a href="{% url 'blog:post_list' %}">My Django Blog</a></h1>
    <nav>
      {% if user.is_authenticated %}
        <a href="{% url 'blog:profile' %}">Profile</a> |
        <a href="{% url 'blog:logout' %}">Logout</a>
      {% else %}
        <a href="{% url 'blog:login' %}">Login</a> |
        <a href="{% url 'blog:register' %}">Register</a>
      {% endif %}
    </nav>
  </header>

  <!-- messages -->
  {% if messages %}
    <ul>
      {% for message in messages %}
        <li>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}

  <main>
    {% block content %}{% endblock %}
  </main>
</body>
</html>

django_blog/blog/templates/blog/comment_confirm_delete.html
{% extends 'blog/base.html' %}
{% block title %}Delete Comment{% endblock %}
{% block content %}
  <h2>Delete Comment</h2>
  <p>Are you sure you want to delete this comment?</p>
  <div class="comment">
    <p><strong>{{ object.author.username }}</strong> — {{ object.created_at|date:"M d, Y H:i" }}</p>
    <div>{{ object.content|linebreaks }}</div>
  </div>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
    <a href="{{ object.post.get_absolute_url }}">Cancel</a>
  </form>
{% endblock %}

django_blog/blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}
{% block title %}{% if object %}Edit Comment{% else %}New Comment{% endif %}{% endblock %}

{% block content %}
  <h2>{% if object %}Edit Comment{% else %}New Comment{% endif %}</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
    <a href="{% if object %}{{ object.post.get_absolute_url }}{% else %}{{ view.post.get_absolute_url }}{% endif %}">Cancel</a>
  </form>
{% endblock %}

django_blog/blog/templates/blog/logged_out.html
{% extends 'blog/base.html' %}
{% block title %}Logged out{% endblock %}
{% block content %}
  <p>You have been logged out.</p>
  <a href="{% url 'blog:login' %}">Login again</a>
{% endblock %}

django_blog/blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

django_blog/blog/templates/blog/post_by_tag.html
{% extends "base.html" %}

{% block content %}
  <h2>Posts tagged with "{{ tag.name }}"</h2>
  <ul>
    {% for post in posts %}
      <li>
        <a href="{% url 'post-detail' post.pk %}">{{ post.title }}</a>
      </li>
    {% empty %}
      <li>No posts found with this tag.</li>
    {% endfor %}
  </ul>
{% endblock %}

django_blog/blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% block title %}Delete Post{% endblock %}

{% block content %}
  <h2>Are you sure you want to delete "{{ object.title }}"?</h2>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
    <a href="{{ object.get_absolute_url }}">Cancel</a>
  </form>
{% endblock %}

django_blog/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<p>Tags:
  {% for tag in post.tags.all %}
    <a href="{% url 'posts_by_tag' tag.slug %}">{{ tag.name }}</a>{% if not forloop.last %}, {% endif %}
  {% empty %}
    No tags
  {% endfor %}
</p>

  <article>
    <h2>{{ post.title }}</h2>
    <p>By {{ post.author }} — {{ post.published_date|date:"M d, Y H:i" }}</p>
    <div>{{ post.content|linebreaks }}</div>
  </article>

  <section id="comments">
    <h3>Comments ({{ post.comments.count }})</h3>

    {% for comment in post.comments.all %}
      <div class="comment" style="border-bottom:1px solid #ddd; padding:8px 0;">
        <p><strong>{{ comment.author.username }}</strong> — <small>{{ comment.created_at|date:"M d, Y H:i" }}</small></p>
        <div>{{ comment.content|linebreaks }}</div>
        {% if user == comment.author %}
          <p>
            <a href="{% url 'blog:comment_update' post.pk comment.pk %}">Edit</a> |
            <a href="{% url 'blog:comment_delete' post.pk comment.pk %}">Delete</a>
          </p>
        {% endif %}
      </div>
    {% empty %}
      <p>No comments yet.</p>
    {% endfor %}
  </section>

  <section id="add-comment">
    <h3>Leave a comment</h3>
    {% if user.is_authenticated %}
      <form action="{% url 'blog:comment_create' post.pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}       {# form يجب أن يمرّر من view أو يمكن إنشاؤه في القالب #}
        <button type="submit">Post Comment</button>
      </form>
    {% else %}
      <p><a href="{% url 'blog:login' %}">Login</a> to leave a comment.</p>
    {% endif %}
  </section>
{% endblock %}

django_blog/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% block title %}{% if object %}Edit Post{% else %}New Post{% endif %}{% endblock %}

{% block content %}
  <h2>{% if object %}Edit Post{% else %}New Post{% endif %}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

django_blog/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block title %}All Posts{% endblock %}

{% block content %}
  <h2>All Blog Posts</h2>
  {% if user.is_authenticated %}
    <a href="{% url 'blog:post_create' %}">Create New Post</a>
  {% endif %}
  <ul>
    {% for post in posts %}
      <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        by {{ post.author }} on {{ post.published_date|date:"M d, Y" }}
      </li>
    {% empty %}
      <li>No posts yet.</li>
    {% endfor %}
  </ul>
{% endblock %}

django_blog/blog/templates/blog/post_search.html
{% extends "base.html" %}

{% block content %}
  <h2>Search Results</h2>
  {% if query %}
    <p>Results for "{{ query }}":</p>
    <ul>
      {% for post in results %}
        <li>
          <a href="{% url 'post-detail' post.pk %}">{{ post.title }}</a>
        </li>
      {% empty %}
        <li>No results found.</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>Please enter a search query.</p>
  {% endif %}
{% endblock %}

django_blog/blog/templates/blog/profile.html
{% extends 'blog/base.html' %}
{% block title %}Profile{% endblock %}
{% block content %}
  <h2>Profile</h2>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h3>Account</h3>
    {{ u_form.as_p }}
    <h3>Profile</h3>
    {{ p_form.as_p }}
    <button type="submit">Save changes</button>
  </form>
{% endblock %}

django_blog/blog/templates/blog/register.html
{% extends 'blog/base.html' %}
{% block title %}Register{% endblock %}
{% block content %}
  <h2>Register</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
{% endblock %}